import type { Metadata } from 'next';
import {
  JetBrains_Mono,
  Sofia_Sans,
  Sofia_Sans_Semi_Condensed,
} from 'next/font/google';
import './globals.css';

const fontBody = Sofia_Sans_Semi_Condensed({
  variable: '--font-body',
  subsets: ['latin'],
});

const fontDisplay = Sofia_Sans({
  variable: '--font-display',
  subsets: ['latin'],
});

const fontCode = JetBrains_Mono({
  variable: '--font-code',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Spotify Pass',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-US">
      <body
        className={`${fontBody.variable} ${fontDisplay.variable} ${fontCode.variable} font-body bg-neutral-950 text-neutral-50 antialiased`}
      >
        <div className="flex min-h-screen flex-col p-8">
          {/* HEADER */}
          <div className="mx-auto flex w-full max-w-2xl grow flex-col">
            <main className="my-24 grow text-pretty break-words md:my-36">
              {children}
            </main>
          </div>
          {/* FOOTER */}
        </div>
      </body>
    </html>
  );
}
